/******************************************************************************
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2026 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Compiled implementation of the executable rewrite rules.
 *
 * This file is generated by `-o rare-db-exec` and installed by
 * contrib/install-rare-rewrites. Do not edit it by hand; edit the RARE
 * rules marked with :exec and regenerate it.
 */

#include "rewriter/rewrite_db_exec.h"

#include "expr/node_manager.h"
#include "util/bitvector.h"
#include "util/rational.h"
#include "util/string.h"

namespace cvc5::internal {
namespace rewriter {

RewriteDbExec::RewriteDbExec(NodeManager* nm) : d_nm(nm)
{
  // RegLan
  d_types.push_back(d_nm->regExpType());
}

bool RewriteDbExec::empty() const { return false; }

void RewriteDbExec::getMatches(
    const Node& n,
    std::vector<ExecMatch>& matches) const
{
  switch (n.getKind())
  {
    case Kind::REGEXP_STAR:
      // re-star-star: (re.* (re.* x1290))
      if (n.getNumChildren() == 1
          && n[0].getKind() == Kind::REGEXP_STAR
          && n[0].getNumChildren() == 1
          && n[0][0].getType().isComparableTo(d_types[0]))
      {
        matches.push_back(ExecMatch{
            ProofRewriteRule::RE_STAR_STAR, {n[0][0]}});
      }
      break;
    default: break;
  }
}

size_t RewriteDbExec::getNumConditions(
    CVC5_UNUSED const ExecMatch& m) const
{
  switch (m.d_id)
  {
    default: break;
  }
  return 0;
}

Node RewriteDbExec::getCondition(
    CVC5_UNUSED const ExecMatch& m,
    CVC5_UNUSED size_t i) const
{
  switch (m.d_id)
  {
    default: break;
  }
  return Node::null();
}

Node RewriteDbExec::getResult(
    const ExecMatch& m) const
{
  switch (m.d_id)
  {
    case ProofRewriteRule::RE_STAR_STAR:
      return d_nm->mkNode(Kind::REGEXP_STAR, {m.d_subs[0]});
    default: break;
  }
  return Node::null();
}

}  // namespace rewriter
}  // namespace cvc5::internal
