/******************************************************************************
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2026 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Compiled implementation of the executable rewrite rules.
 *
 * This file is generated by `-o rare-db-exec` and installed by
 * contrib/install-rare-rewrites. Do not edit it by hand; edit the RARE
 * rules marked with :exec and regenerate it.
 */

#include "rewriter/rewrite_db_exec_compiled.h"

#include "expr/node_manager.h"
#include "util/bitvector.h"
#include "util/rational.h"
#include "util/string.h"

namespace cvc5::internal {
namespace rewriter {

RewriteDbExecCompiled::RewriteDbExecCompiled(NodeManager* nm) : d_nm(nm) {}

bool RewriteDbExecCompiled::empty() const { return true; }

void RewriteDbExecCompiled::getMatches(
    CVC5_UNUSED const Node& n,
    CVC5_UNUSED std::vector<CompiledExecMatch>& matches) const
{
  // there are no :exec rules
}

size_t RewriteDbExecCompiled::getNumConditions(
    CVC5_UNUSED const CompiledExecMatch& m) const
{
  return 0;
}

Node RewriteDbExecCompiled::getCondition(CVC5_UNUSED const CompiledExecMatch& m,
                                         CVC5_UNUSED size_t i) const
{
  return Node::null();
}

Node RewriteDbExecCompiled::getResult(
    CVC5_UNUSED const CompiledExecMatch& m) const
{
  return Node::null();
}

}  // namespace rewriter
}  // namespace cvc5::internal
